"use client";

// import { useState } from "react";
import { Providers } from "./providers";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import React from "react";
import { BiChevronDown } from "react-icons/bi";
import { Space } from "antd";
import {
  Dropdown,
  DropdownTrigger,
  DropdownMenu,
  DropdownItem,
  Button,
  Avatar,
  User,
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  NavbarMenuToggle,
  NavbarMenu,
  NavbarMenuItem,
} from "@nextui-org/react";
// import { Avatar } from "antd";
import {
  TwitterOutlined,
  GithubOutlined,
  FacebookOutlined,
  DiscordFilled,
} from "@ant-design/icons";
import Link from "next/link";
// import type { Metadata } from "next";
// import DropdownMenu from "/components"; // Adjust the path based on your project structure

const inter = Inter({ subsets: ["latin"] });
const url =
  "https://st3.depositphotos.com/15648834/17930/v/450/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg";

// export const metadata: Metadata = {
//   title: "NimeList",
//   description: "Generated by create next app",
// };

const items = [
  {
    label: (
      <Link className="text-white" href="/action">
        Action
      </Link>
    ),
    key: "1",
  },
  {
    label: (
      <Link className="text-white" href="/adventure">
        Adventure
      </Link>
    ),
    key: "2",
  },
  {
    label: (
      <Link className="text-white" href="#">
        Avant Garde
      </Link>
    ),
    key: "3",
  },
  {
    label: (
      <Link className="text-white" href="#">
        Comedy
      </Link>
    ),
    key: "4",
  },
  {
    label: (
      <Link className="text-white" href="#">
        Drama
      </Link>
    ),
    key: "5",
  },
  {
    label: (
      <Link className="text-white" href="#">
        Isekai
      </Link>
    ),
    key: "6",
  },
  {
    label: (
      <Link className="text-white" href="#">
        Josei
      </Link>
    ),
    key: "7",
  },
  {
    label: (
      <Link className="text-white" href="#">
        Magic
      </Link>
    ),
    key: "8",
  },
  {
    label: (
      <Link className="text-white" href="#">
        Martial Arts
      </Link>
    ),
    key: "9",
  },
  {
    label: (
      <Link className="text-white" href="#">
        Mecha
      </Link>
    ),
    key: "10",
  },
];

const menuItems = [
  {
    key: "1",
    label: (
      <Link className="text-white" href="/membership">
        Membership
      </Link>
    ),
  },
  {
    key: "2",
    label: (
      <Link className="text-white" href="/favorites">
        Your Favorites
      </Link>
    ),
  },
  {
    key: "3",
    label: (
      <Link className="text-white" href="/search">
        Search Anime
      </Link>
    ),
  },
];
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isMenuOpen, setIsMenuOpen] = React.useState(false);
  return (
    <html>
      <head>
        <title>NimeList</title>
        <link rel="icon" href="/images/favicon.ico" />
      </head>
      <body className={inter.className}>
        <Navbar
          onMenuOpenChange={setIsMenuOpen}
          className="bg-transparent"
          maxWidth="full"
        >
          <NavbarContent justify="start">
            <NavbarMenuToggle
              aria-label={isMenuOpen ? "Close menu" : "Open menu"}
              className="sm:hidden"
            />
            <NavbarItem className="ml-7">
              <Link
                href="/"
                className="flex items-center justify-center w-12 h-7 cursor-pointer"
              >
                <Image
                  src="/images/logo.png"
                  alt="logo"
                  width={48}
                  height={28}
                  className="block"
                />
              </Link>
            </NavbarItem>
            <NavbarItem className="hidden md:flex">
              <Dropdown
                backdrop="blur"
                placement="bottom-start"
                classNames={{
                  content: "bg-[#00554B]",
                }}
              >
                <DropdownTrigger className="text-white">
                  <Button variant="light" size="lg">
                    Browse
                    <BiChevronDown
                      style={{ fontSize: "20px", color: "white" }}
                    />
                  </Button>
                </DropdownTrigger>
                <DropdownMenu
                  aria-label="Static Actions"
                  itemClasses={{
                    base: [
                      "data-[hover=true]:bg-teal-500",
                      "dark:data-[hover=true]:bg-teal-700",
                    ],
                  }}
                >
                  {/* Map through the items array and create DropdownItem for each */}
                  {items.map((item) => (
                    <DropdownItem key={item.key} className="opacity-100">
                      {item.label}
                    </DropdownItem>
                  ))}
                </DropdownMenu>
              </Dropdown>
            </NavbarItem>
          </NavbarContent>
          <NavbarContent className="flex items-center space-x-6" justify="end">
            <ul className="hidden md:flex items-center space-x-[50px]">
              <li>
                <Link href="/membership" className="block">
                  <Image
                    src="/images/crown.svg"
                    alt="membership"
                    width={29}
                    height={32}
                    priority
                    className="cursor-pointer"
                  />
                </Link>
              </li>
              <li>
                <Link href="/favorites">
                  <Image
                    src="/images/bookmark.svg"
                    alt="bookmark"
                    width={29}
                    height={32}
                    priority
                    className="cursor-pointer"
                  />
                </Link>
              </li>
              <li>
                <Link href="/search">
                  <Image
                    src="/images/magnifying.svg"
                    alt="search"
                    width={29}
                    height={32}
                    priority
                    className="cursor-pointer"
                  />
                </Link>
              </li>
            </ul>
            <div className="flex pr-10 pl-10">
              <Dropdown
                placement="bottom-end"
                backdrop="blur"
                classNames={{ content: "bg-[#00554B]" }}
              >
                <DropdownTrigger>
                  <Avatar
                    isBordered
                    as="button"
                    className="transition-transform"
                    src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
                  />
                </DropdownTrigger>
                <DropdownMenu
                  aria-label="Profile Actions"
                  variant="flat"
                  style={{ userSelect: "none" }}
                  itemClasses={{
                    base: [
                      "data-[hover=true]:bg-teal-500",
                      "dark:data-[hover=true]:bg-teal-700",
                    ],
                  }}
                >
                  <DropdownItem
                    key="profile"
                    isReadOnly
                    className="h-14 gap-2 opacity-100"
                  >
                    <User
                      name="Junior Garcia"
                      description="@jrgarciadev"
                      classNames={{
                        name: "text-white",
                        description: "text-white",
                      }}
                      avatarProps={{
                        size: "sm",
                        src: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
                      }}
                    />
                  </DropdownItem>
                  <DropdownItem
                    key="profile"
                    className="dark:hover:text-white"
                    href="/profile"
                  >
                    My Profile
                  </DropdownItem>
                  <DropdownItem
                    key="team_settings"
                    className="dark:hover:text-white"
                    href="#"
                  >
                    Team Settings
                  </DropdownItem>
                  <DropdownItem key="logout" color="danger">
                    <p className="font-semibold">Log Out</p>
                  </DropdownItem>
                </DropdownMenu>
              </Dropdown>
            </div>
          </NavbarContent>
          <NavbarMenu className={`${isMenuOpen ? 'bg-black' : ''}`}>
              {menuItems.map((item) => (
                <NavbarMenuItem key={item.key}>{item.label}</NavbarMenuItem>
              ))}
            </NavbarMenu>
        </Navbar>
        {/* </div> */}
        {/* </header> */}

        <main className="min-h-screen bg-dark-100">{children}</main>

        <footer className="w-full bg-[#0B0B0B]">
          <div className="mx-auto w-full max-w-screen-xl">
            <div className="grid grid-cols-2 gap-8 px-4 py-6 lg:py-8 md:grid-cols-5">
              <div>
                <Image
                  src="/images/logo.png"
                  alt="Nimelist_logo"
                  width={40}
                  height={40}
                  className="flex ml-10 mb-5 sm:justify-center md:mt-0 filter brightness-0 invert"
                  priority
                />
                <div className="flex mt-4 sm:justify-center md:mt-0 space-x-5 rtl:space-x-reverse">
                  <Link
                    href="#"
                    className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
                  >
                    <FacebookOutlined width={20} height={20} />
                    <span className="sr-only">Facebook page</span>
                  </Link>
                  <Link
                    href="#"
                    className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
                  >
                    <DiscordFilled />
                    <span className="sr-only">Discord community</span>
                  </Link>
                  <Link
                    href="#"
                    className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
                  >
                    <TwitterOutlined />
                    <span className="sr-only">Twitter page</span>
                  </Link>
                  <Link
                    href="#"
                    className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
                  >
                    <GithubOutlined />
                    <span className="sr-only">GitHub account</span>
                  </Link>
                </div>
              </div>
              <div>
                <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">
                  Navigation
                </h2>
                <ul className="text-gray-500 dark:text-gray-400 font-medium">
                  <li className="mb-4">
                    <Link href="#" className=" hover:underline">
                      Browse Popular
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      New Release
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Search
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Brand Center
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">
                  Connect with us
                </h2>
                <ul className="text-gray-500 dark:text-gray-400 font-medium">
                  <li className="mb-4">
                    <Link href="#" className=" hover:underline">
                      Discord Server
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Twitter
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Facebook
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Contact Us
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">
                  Legal
                </h2>
                <ul className="text-gray-500 dark:text-gray-400 font-medium">
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Privacy Policy
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Licensing
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Terms &amp; Conditions
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">
                  Account
                </h2>
                <ul className="text-gray-500 dark:text-gray-400 font-medium">
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Log in
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Create Account
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
            <div className="px-4 py-6 bg-transparent dark:bg-transparent md:flex md:items-center md:justify-center">
              <span className="text-sm text-gray-500 dark:text-gray-150 sm:text-center">
                © 2024 <Link href="https://localhost.3000/">NimeList™</Link>.
                All Rights Reserved.
              </span>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
