"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import React from "react";
import { DownOutlined } from "@ant-design/icons";
import type { MenuProps } from "antd";
import { Dropdown, Space } from "antd";
import { Avatar } from "antd";
import {
  TwitterOutlined,
  GithubOutlined,
  FacebookOutlined,
  DiscordFilled,
} from "@ant-design/icons";
import Link from "next/link";
// import type { Metadata } from "next";
// import DropdownMenu from "/components"; // Adjust the path based on your project structure

const inter = Inter({ subsets: ["latin"] });
const url =
  "https://st3.depositphotos.com/15648834/17930/v/450/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg";

// export const metadata: Metadata = {
//   title: "NimeList",
//   description: "Generated by create next app",
// };

const items: MenuProps["items"] = [
  {
    label: <Link href="#">Action</Link>,
    key: "0",
  },
  {
    label: <Link href="#">Adventure</Link>,
    key: "1",
  },
  {
    label: <Link href="#">Avant Garde</Link>,
    key: "2",
  },
  {
    label: <Link href="#">Comedy</Link>,
    key: "3",
  },
  {
    label: <Link href="#">Drama</Link>,
    key: "4",
  },
  {
    label: <Link href="#">Isekai</Link>,
    key: "5",
  },
  {
    label: <Link href="#">Josei</Link>,
    key: "6",
  },
  {
    label: <Link href="#">Magic</Link>,
    key: "7",
  },
  {
    label: <Link href="#">Martial Arts</Link>,
    key: "8",
  },
  {
    label: <Link href="#">Mecha</Link>,
    key: "9",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>NimeList</title>
        <link rel="icon" href="/images/favicon.ico" />
      </head>
      <body className={inter.className}>
        <header className="w-full h-[77px] bg-transparent">
          <div className="flex h-full mx-auto">
            <nav className="flex items-center h-full w-full">
              <div className="flex ml-5 h-full w-full">
                <Link
                  href="/"
                  className="flex items-center justify-center w-12 h-7 mt-6 ml-10 cursor-pointer"
                >
                  <Image
                    src="/images/logo.png"
                    alt="logo"
                    width={48}
                    height={28}
                  />
                </Link>
                <ul className="flex items-center ">
                  <li className="flex items-center ml-5 px-4 text-white text-xl font-medium cursor-pointer">
                    <Dropdown
                      overlayClassName="custom-dropdown-menu"
                      menu={{ items }}
                      trigger={["click"]}
                    >
                      <a onClick={(e) => e.preventDefault()}>
                        <Space style={{ userSelect: "none" }}>
                          Browse
                          <DownOutlined style={{ fontSize: "12px" }} />
                        </Space>
                      </a>
                    </Dropdown>
                  </li>
                </ul>
              </div>
              <div className="flex flex-row-reverse items-center w-full space-x-11">
                <ul className="flex items-center space-x-20">
                  <li>
                    <Link href="/membership" className="m-auto block">
                      <Image
                        src="/images/crown.svg"
                        alt="membership"
                        width={29}
                        height={32}
                        priority
                        className="block cursor-pointer m-auto"
                      />
                    </Link>
                  </li>
                  <li>
                    <Link href="/favorites">
                      <Image
                        src="/images/bookmark.svg"
                        alt="bookmark"
                        width={29}
                        height={32}
                        priority
                        className="cursor-pointer"
                      />
                    </Link>
                  </li>
                  <li>
                    <Link href="/search">
                      <Image
                        src="/images/magnifying.svg"
                        alt="search"
                        width={29}
                        height={32}
                        priority
                        className="cursor-pointer"
                      />
                    </Link>
                  </li>
                  <li>
                    <div className="flex mr-10 ">
                      <Space size={20} wrap>
                        <Avatar
                          size={45}
                          src={
                            <img
                              src={url}
                              alt="avatar"
                              style={{
                                cursor: "pointer",
                              }}
                            />
                          }
                        />
                      </Space>
                    </div>
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </header>

        <main className="min-h-screen bg-dark-100">{children}</main>

        <footer className="w-full bg-[#0B0B0B]">
          <div className="mx-auto w-full max-w-screen-xl">
            <div className="grid grid-cols-2 gap-8 px-4 py-6 lg:py-8 md:grid-cols-5">
              <div>
                <Image
                  src="/images/logo.png"
                  alt="Nimelist_logo"
                  width={40}
                  height={40}
                  className="flex ml-10 mb-5 sm:justify-center md:mt-0 filter brightness-0 invert"
                  priority
                />
                <div className="flex mt-4 sm:justify-center md:mt-0 space-x-5 rtl:space-x-reverse">
                  <Link
                    href="#"
                    className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
                  >
                    <FacebookOutlined width={20} height={20} />
                    <span className="sr-only">Facebook page</span>
                  </Link>
                  <Link
                    href="#"
                    className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
                  >
                    <DiscordFilled />
                    <span className="sr-only">Discord community</span>
                  </Link>
                  <Link
                    href="#"
                    className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
                  >
                    <TwitterOutlined />
                    <span className="sr-only">Twitter page</span>
                  </Link>
                  <Link
                    href="#"
                    className="text-gray-400 hover:text-gray-900 dark:hover:text-white"
                  >
                    <GithubOutlined />
                    <span className="sr-only">GitHub account</span>
                  </Link>
                </div>
              </div>
              <div>
                <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">
                  Navigation
                </h2>
                <ul className="text-gray-500 dark:text-gray-400 font-medium">
                  <li className="mb-4">
                    <Link href="#" className=" hover:underline">
                      Browse Popular
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      New Release
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Search
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Brand Center
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">
                  Connect with us
                </h2>
                <ul className="text-gray-500 dark:text-gray-400 font-medium">
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Discord Server
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Twitter
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Facebook
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Contact Us
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">
                  Legal
                </h2>
                <ul className="text-gray-500 dark:text-gray-400 font-medium">
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Privacy Policy
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Licensing
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Terms &amp; Conditions
                    </Link>
                  </li>
                </ul>
              </div>
              <div>
                <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">
                  Account
                </h2>
                <ul className="text-gray-500 dark:text-gray-400 font-medium">
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Log in
                    </Link>
                  </li>
                  <li className="mb-4">
                    <Link href="#" className="hover:underline">
                      Create Account
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
            <div className="px-4 py-6 bg-transparent dark:bg-transparent md:flex md:items-center md:justify-center">
              <span className="text-sm text-gray-500 dark:text-gray-150 sm:text-center">
                © 2024 <Link href="https://localhost.3000/">NimeList™</Link>. All
                Rights Reserved.
              </span>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
