import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NimeList",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>NimeList</title>
        <link rel="icon" href="/images/favicon.ico" className="size-" />
      </head>
      <body className={inter.className}>
        <header className="w-full h-[77px] bg-transparent">
          <div className="flex h-full mx-auto">
            <nav className="flex items-center h-full w-full">
              <div className="flex space-x-5 ml-5 h-full w-full">
                <a
                  href="/"
                  className="flex items-center justify-center w-12 h-7 mt-6 ml-10 size-10 cursor-pointer"
                >
                  <img
                    src="/images/logo.png"
                    alt="logo"
                    className="flex items-center justify-center"
                  />
                  {/* <Image
                    src="/images/logo.png"
                    alt="logo"
                    width={100}
                    height={100}
                  /> */}
                </a>
                <ul className="flex items-center">
                  <li className="flex items-center justify-start px-4 text-white text-xl font-medium">
                    Browse
                    <Image
                      src="/images/dropdown.svg"
                      alt="dropdown arrow"
                      width={20}
                      height={20}
                      priority
                      className="invert-0 ml-1"
                    />
                  </li>
                </ul>
                {/* </div> */}
                {/* <div className="flex items-center justify-end "> */}
                <ul className="flex items-center justify-end">
                  <li>
                    <Image
                      src="/images/bookmark.svg"
                      alt="bookmark"
                      width={25}
                      height={25}
                      priority
                      className="invert-0 m-1"
                    />
                  </li>
                </ul>
              </div>
            </nav>
          </div>
        </header>

        <main className="min-h-screen bg-dark-100">{children}</main>

        <footer className="w-full h-auto bg-gray-900">
          <div className="flex flex-col items-center justify-center h-full px-4 py-8 md:py-16 lg:py-24 max-w-screen-2xl mx-auto">
            <p className="text-white text-lg text-center">
              Footer Content Here
            </p>
            {}
          </div>
        </footer>
      </body>
    </html>
  );
}
